apiVersion: v1
kind: Service
metadata:
  name: appweb-service
  labels:
    app: mi-crud
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
  selector:
    app: mi-crud